image: "Visual Studio 2019"

version: '{build}'

build_script:
  - '.\build.cmd'

test: "off"

artifacts:
  - name: Packages
    path: '.\artifacts\*.nupkg'
  - name: Symbols
    path: '.\artifacts\*.snupkg'
