name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300

      - name: Cache NuGet Packages
        uses: actions/cache@v2.0.0
        with:
          path: packages
          key: Packages

      - name: Build .NET Solution
        uses: Chakrygin/dotnet-build-action

      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: artifacts/*.nupkg
