name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONFIGURATION: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.400

      - name: Cache NuGet Packages
        uses: actions/cache@v2.0.0
        with:
          path: packages
          key: Packages

      - name: Build .NET Solution
        run: |
          dotnet restore --packages "packages"

          dotnet build --nologo --no-restore --configuration "$CONFIGURATION"

          dotnet test --nologo --no-build --configuration "$CONFIGURATION" "tests/DiagnosticsNet.Tests/DiagnosticsNet.Tests.csproj"

          dotnet pack --nologo --no-build --configuration "$CONFIGURATION" --output "artifacts" "src/DiagnosticsNet/DiagnosticsNet.csproj"
          dotnet pack --nologo --no-build --configuration "$CONFIGURATION" --output "artifacts" "src/DiagnosticsNet.Abstractions/DiagnosticsNet.Abstractions.csproj"

      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: artifacts/*.nupkg
